name: .NET Build, Test, Publish

on:
  push:
    branches: [ "main", "create-app-service" ]
    
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./webbap/TodosApp.sln -c Release
    - name: Build
      run: dotnet build ./webbap/TodosApp.sln --no-restore -c Release
    - name: Test
      run: dotnet test ./webbap/TodosApp.sln --no-build --verbosity normal -c Release
    - name: Publish
      run: dotnet publish  ./webbap/TodosApp.Web/TodosApp.Web.csproj --no-build --verbosity normal -c Release
  
